<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Upload pieces</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/styles.css"></head>
<body><div class="app-layout"><jsp:include page="/WEB-INF/views/layout/navbar.jsp" /><main class="main-content">
<div class="stepper"><c:forEach begin="1" end="7" var="i"><div class="stepper-item ${i == etapeActuelle ? 'active' : (i < etapeActuelle ? 'done' : 'future')}"><div><div class="stepper-node">${i}</div></div><c:if test="${i < 7}"><div class="stepper-track"></div></c:if></div></c:forEach></div>
<c:if test="${not empty succes}"><div class="alert-succes">${succes}</div></c:if><c:if test="${not empty erreur}"><div class="alert-erreur">${erreur}</div></c:if>
<h1 class="page-title">Upload des pieces - Dossier n${demande.id}</h1>
<p class="page-subtitle">${demande.demandeur.nom} ${demande.demandeur.prenom} - ${demande.typeVisa.libelle}</p>
<section class="card"><h2>Pieces communes</h2><div class="table-wrap"><table class="scan-table"><thead><tr><th>Piece</th><th>Obligatoire</th><th>Statut</th><th>Dernier fichier</th><th>Date upload</th><th>Actions</th></tr></thead><tbody><c:forEach var="piece" items="${piecesCommunes}"><tr><td>${piece.typePieceCommune.libelle}</td><td><span class="badge badge-neutre">${piece.typePieceCommune.obligatoire ? 'Obligatoire' : 'Optionnelle'}</span></td><td><span class="badge ${piece.uploaded ? 'badge-succes' : 'badge-danger'}">${piece.uploaded ? 'Uploade' : 'En attente'}</span></td><td>${not empty derniersUploadsCommunes[piece.id] ? derniersUploadsCommunes[piece.id].nomFichierOriginal : '-'}</td><td>${not empty derniersUploadsCommunes[piece.id] ? derniersUploadsCommunes[piece.id].dateUpload : '-'}</td><td><form method="post" action="${pageContext.request.contextPath}/demande/autre/etape4/piece" enctype="multipart/form-data" class="upload-inline-form"><input type="hidden" name="idPiece" value="${piece.id}"/><input type="hidden" name="typePiece" value="commune"/><input type="file" name="fichier" accept=".jpg,.jpeg,.png,.pdf" required/><input type="date" name="dateUpload" value="${today}" required/><button type="submit" class="btn btn-primary btn-sm">Soumettre</button></form></td></tr></c:forEach></tbody></table></div></section>
<section class="card" style="margin-top:1rem;"><h2>Pieces specifiques</h2><div class="table-wrap"><table class="scan-table"><thead><tr><th>Piece</th><th>Obligatoire</th><th>Statut</th><th>Dernier fichier</th><th>Date upload</th><th>Actions</th></tr></thead><tbody><c:forEach var="piece" items="${piecesSpecifiques}"><tr><td>${piece.typePiece.libelle}</td><td><span class="badge badge-neutre">${piece.typePiece.obligatoire ? 'Obligatoire' : 'Optionnelle'}</span></td><td><span class="badge ${piece.uploaded ? 'badge-succes' : 'badge-danger'}">${piece.uploaded ? 'Uploade' : 'En attente'}</span></td><td>${not empty derniersUploadsSpecifiques[piece.id] ? derniersUploadsSpecifiques[piece.id].nomFichierOriginal : '-'}</td><td>${not empty derniersUploadsSpecifiques[piece.id] ? derniersUploadsSpecifiques[piece.id].dateUpload : '-'}</td><td><form method="post" action="${pageContext.request.contextPath}/demande/autre/etape4/piece" enctype="multipart/form-data" class="upload-inline-form"><input type="hidden" name="idPiece" value="${piece.id}"/><input type="hidden" name="typePiece" value="specifique"/><input type="file" name="fichier" accept=".jpg,.jpeg,.png,.pdf" required/><input type="date" name="dateUpload" value="${today}" required/><button type="submit" class="btn btn-primary btn-sm">Soumettre</button></form></td></tr></c:forEach></tbody></table></div>
<div class="actions" style="margin-top:1rem;"><c:choose><c:when test="${peutContinuer}"><a href="${pageContext.request.contextPath}/demande/autre/etape5" class="btn btn-primary">Continuer -> Informations du titre</a></c:when><c:otherwise><button type="button" class="btn btn-secondary" disabled>Continuer -></button><p class="texte-erreur">Uploadez toutes les pieces obligatoires pour continuer.</p></c:otherwise></c:choose></div>
</section></main></div></body></html>
